### ISSUE TITLE
Trained models unavailable

### ISSUE THREAD

**Issue by xydisla** [pwoznicki/ADPKD#1]
I'm not able to access the trained models on OneDrive, would you be able to reupload?

**Comment by pwoznicki** [comment]
Hi @xydisla,

thank for pointing that out. I updated the link to the trained models in README. Let me know if you have any problems.

You can also download the prebuilt Docker image which includes those trained models with:
```
$ docker pull piotrekwoznicki/adpkd-net:v0.1
```
